### ISSUE TITLE
Oxygen-Oxygen graph marker not visible at lowest point

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#27]
When you switch to the Oxygen-Oxygen pair, the marker showing the position of the moveable atom is not visible on the graph even when fully zoomed out, and it should be, just as it is for any other pair of atoms.
![screen shot 2015-03-02 at 3 59 43 pm](https://cloud.githubusercontent.com/assets/4682895/6452781/2d013f82-c0f5-11e4-97f9-75efe4600ba4.png)

If needed, adjust the scaling of the vertical axis to make sure that the "dot" is visible on the graph when fully zoomed out.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
The fix looks like it might have led to a bit of buggy behavior. If you zoom out fully, and then start dragging the oxygen atom, the marker does not travel smoothly along the curve on the graph like it did in the Java version. There is a point where the marker still disappears.

![untitled](https://cloud.githubusercontent.com/assets/4682895/6657685/950222a4-cb18-11e4-9525-0d27aa863f7b.gif)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Behaviour is still not consistent with what might be expected in the Java sim, and the marker does not travel smoothly along the curve when the atom is dragged.

I am not certain if this is due to estimations required to position the atom in this much deeper well, but the marker should move smoothly tracking along a roughly parabolic path.

Currently, moves almost directly horizontally at one point near the bottom of the curve, similar to what's shown in the video above.

**Comment by ycarpenterphet** [comment]
@ChandrashekarBemagoni Can you comment on how things are progressing with this issue?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Fantastic. Closing.
